instrumentation:
    root: ./app
    extensions:
        - .js
        - .jsx
    excludes: [
      '**/*-test.js',
      '**/*-test.jsx',
      '**/*.marko.js',
      'app.jsx',
      'routes.jsx',
      'server.js',
      'client/mutations/**/*.js',
      'client/queries/**/*.js',
      'client/test-helpers/**/*.js',
      'client/test-helpers/**/*.jsx',
      'client/libs/**/*.js'
    ]
    include-all-sources: true
    es-modules: true
